const images = [
  { src: `63.jpg`, title: "Image 63", category: "default" },
  {
    src: "1.jpg",
    title: "Republic Day celebrations across our office spaces",
    category: "default",
    null: null,
  },
  {
    src: "2.jpg",
    title: "Republic Day celebrations across our office spaces",
    category: "default",
    null: null,
  },
  {
    src: "3.jpg",
    title: "Republic Day celebrations across our office spaces",
    category: "default",
    null: null,
  },
  {
    src: "4.jpg",
    title: "Republic Day celebrations across our office spaces",
    category: "default",
    null: null,
  },
  {
    src: "5.jpg",
    title: "Republic Day celebrations at Jio World Centre",
    category: "default",
    null: null,
  },
  {
    src: "6.jpg",
    title: "Republic Day celebrations at Jio Institute",
    category: "default",
    null: null,
  },
  {
    src: "7.jpg",
    title: "Republic Day celebrations at Dhirubhai Ambani Square, NMACC",
    category: "default",
    null: null,
  },
  {
    src: "8.jpg",
    title: "Republic Day celebrations at Jio",
    category: "default",
    null: null,
  },
  {
    src: "9.jpg",
    title: "Republic Day parade at Reliance",
    category: "default",
    null: null,
  },
  {
    src: "10.jpg",
    title: "Glimpses from the Photography Day workshop at RCP, Navi Mumbai",
    category: "default",
    null: null,
  },
  {
    src: "11.jpg",
    title: "Glimpses from the Photography Day workshop at RCP, Navi Mumbai",
    category: "default",
    null: null,
  },
  {
    src: "12.jpg",
    title: "At the International Women’s Day walkathon at RCP, Navi Mumbai",
    category: "default",
    null: null,
  },
  {
    src: "13.jpg",
    title: "A colleague enjoying volleyball",
    category: "default",
    null: null,
  },
  {
    src: "14.jpg",
    title: "A colleague enjoying volleyball",
    category: "default",
    null: null,
  },
  {
    src: "15.jpg",
    title: "Colleagues enjoying foosball",
    category: "default",
    null: null,
  },
  {
    src: "16.jpg",
    title: "A Reliance colleague and his family exploring the RCP campus",
    category: "default",
    null: null,
  },
  {
    src: "17.jpg",
    title: "Sustainable Fashion Show at RCP, Navi Mumbai, organised to mark Environment Day celebrations",
    category: "default",
    null: null,
  },
  {
    src: "18.jpg",
    title: "Sustainable Fashion Show at RCP, Navi Mumbai, organised to mark Environment Day celebrations",
    category: "default",
    null: null,
  },
  {
    src: "19.jpg",
    title: "Colleagues with their certificates following a blood donation drive",
    category: "default",
    null: null,
  },
  {
    src: "20.jpg",
    title: "Colleagues playing badminton",
    category: "default",
    null: null,
  },
  {
    src: "21.jpg",
    title: "At the Jio Mumbai Sustainability Cyclothon",
    category: "default",
    null: null,
  },
  {
    src: "22.jpg",
    title: "Independence Day celebrations at Jio",
    category: "default",
    null: null,
  },
  {
    src: "23.jpg",
    title: "Some of our colleagues with a furry friend on campus",
    category: "default",
    null: null,
  },
  {
    src: "24.jpg",
    title: "Some of our colleagues with a furry friend on campus",
    category: "default",
    null: null,
  },
  {
    src: "25.jpg",
    title: "Upcycling activities at RCP, Navi Mumbai",
    category: "default",
    null: null,
  },
  {
    src: "26.jpg",
    title: "Colleagues celebrate Onam",
    category: "default",
    null: null,
  },
  {
    src: "27.jpg",
    title: "Colleagues celebrate Onam",
    category: "default",
    null: null,
  },
  {
    src: "28.jpg",
    title: "Flower rangoli as part of Onam celebrations",
    category: "default",
    null: null,
  },
  {
    src: "29.jpg",
    title: "A colleague from Reliance Jewels, Viviana Mall, Thane, is all smiles during the festive season",
    category: "default",
    null: null,
  },
  {
    src: "30.jpg",
    title: "Republic Day celebrations at RCP, Navi Mumbai",
    category: "default",
    null: null,
  },
  {
    src: "31.jpg",
    title: "Independence Day celebrations",
    category: "default",
    null: null,
  },
  {
    src: "32.jpg",
    title: "Republic Day celebrations at Reliance Life Sciences, Navi Mumbai",
    category: "default",
    null: null,
  },
  {
    src: "33.jpg",
    title: "A colleague enjoying a swim at RCP, Navi Mumbai",
    category: "default",
    null: null,
  },
  {
    src: "34.jpg",
    title: "Colleagues at the R-Swasthya walkathon",
    category: "default",
    null: null,
  },
  {
    src: "35.jpg",
    title: "Colleagues at the R-Swasthya walkathon",
    category: "default",
    null: null,
  },
  { src: `36.jpg`, title: "Image 36", category: "default" },
  // { src: `37.jpg`, title: "Image 37", category: "default" },
  { src: `38.jpg`, title: "Image 38", category: "default" },
  { src: `39.jpg`, title: "Image 39", category: "default" },
  { src: `40.jpg`, title: "Image 40", category: "default" },
  { src: `41.jpg`, title: "Image 41", category: "default" },
  { src: `42.jpg`, title: "Image 42", category: "default" },
  { src: `43.jpg`, title: "Image 43", category: "default" },
  { src: `44.jpg`, title: "Image 44", category: "default" },
  { src: `45.jpg`, title: "Image 45", category: "default" },
  { src: `46.jpg`, title: "Image 46", category: "default" },
  { src: `47.jpg`, title: "Image 47", category: "default" },
  { src: `48.jpg`, title: "Image 48", category: "default" },
  { src: `49.jpg`, title: "Image 49", category: "default" },
  { src: `50.jpg`, title: "Image 50", category: "default" },
  { src: `51.jpg`, title: "Image 51", category: "default" },
  { src: `52.jpg`, title: "Image 52", category: "default" },
  { src: `53.jpg`, title: "Image 53", category: "default" },
  { src: `54.jpg`, title: "Image 54", category: "default" },
  { src: `55.jpg`, title: "Image 55", category: "default" },
  { src: `56.jpg`, title: "Image 56", category: "default" },
  { src: `57.jpg`, title: "Image 57", category: "default" },
  { src: `58.jpg`, title: "Image 58", category: "default" },
  { src: `59.jpg`, title: "Image 59", category: "default" },
  { src: `60.jpg`, title: "Image 60", category: "default" },
  { src: `61.jpg`, title: "Image 61", category: "default" },
  { src: `62.jpg`, title: "Image 62", category: "default" },

  { src: `64.jpg`, title: "Image 64", category: "default" },
  { src: `65.jpg`, title: "Image 65", category: "default" },
  { src: `66.jpg`, title: "Image 66", category: "default" },
  { src: `67.jpg`, title: "Image 67", category: "default" },
  { src: `68.jpg`, title: "Image 68", category: "default" },
  { src: `69.jpg`, title: "Image 69", category: "default" },
  { src: `70.jpg`, title: "Image 70", category: "default" },
  { src: `71.jpg`, title: "Image 71", category: "default" },
  { src: `72.jpg`, title: "Image 72", category: "default" },
  { src: `73.jpg`, title: "Image 73", category: "default" },
  { src: `74.jpg`, title: "Image 74", category: "default" },
  { src: `75.jpg`, title: "Image 75", category: "default" },
  // { src: `76.jpg`, title: "Image 76", category: "default" },
  { src: `77.jpg`, title: "Image 77", category: "default" },
  { src: `78.jpg`, title: "Image 78", category: "default" },
  { src: `79.jpg`, title: "Image 79", category: "default" },
  { src: `80.jpg`, title: "Image 80", category: "default" },
  { src: `81.jpg`, title: "Image 81", category: "default" },
];

export default images;
