const galleryPath = "img/gallery/";

const images = [
  { src: `${galleryPath}1.jpg`, title: "Image 1", category: "default" },
  { src: `${galleryPath}2.jpg`, title: "Image 2", category: "default" },
  { src: `${galleryPath}3.jpg`, title: "Image 3", category: "default" },
  { src: `${galleryPath}4.jpg`, title: "Image 4", category: "default" },
  { src: `${galleryPath}5.jpg`, title: "Image 5", category: "default" },
  { src: `${galleryPath}6.jpg`, title: "Image 6", category: "default" },
  { src: `${galleryPath}7.jpg`, title: "Image 7", category: "default" },
  { src: `${galleryPath}8.jpg`, title: "Image 8", category: "default" },
  { src: `${galleryPath}9.jpg`, title: "Image 9", category: "default" },
  { src: `${galleryPath}10.jpg`, title: "Image 10", category: "default" },
  { src: `${galleryPath}11.jpg`, title: "Image 11", category: "default" },
  { src: `${galleryPath}12.jpg`, title: "Image 12", category: "default" },
  { src: `${galleryPath}13.jpg`, title: "Image 13", category: "default" },
  { src: `${galleryPath}14.jpg`, title: "Image 14", category: "default" },
  { src: `${galleryPath}15.jpg`, title: "Image 15", category: "default" },
  { src: `${galleryPath}16.jpg`, title: "Image 16", category: "default" },
  { src: `${galleryPath}17.jpg`, title: "Image 17", category: "default" },
  { src: `${galleryPath}18.jpg`, title: "Image 18", category: "default" },
  { src: `${galleryPath}19.jpg`, title: "Image 19", category: "default" },
  { src: `${galleryPath}20.jpg`, title: "Image 20", category: "default" },
  { src: `${galleryPath}21.jpg`, title: "Image 21", category: "default" },
  { src: `${galleryPath}22.jpg`, title: "Image 22", category: "default" },
  { src: `${galleryPath}23.jpg`, title: "Image 23", category: "default" },
  { src: `${galleryPath}24.jpg`, title: "Image 24", category: "default" },
  { src: `${galleryPath}25.jpg`, title: "Image 25", category: "default" },
  { src: `${galleryPath}26.jpg`, title: "Image 26", category: "default" },
  { src: `${galleryPath}27.jpg`, title: "Image 27", category: "default" },
  { src: `${galleryPath}28.jpg`, title: "Image 28", category: "default" },
  { src: `${galleryPath}29.jpg`, title: "Image 29", category: "default" },
  { src: `${galleryPath}30.jpg`, title: "Image 30", category: "default" },
  { src: `${galleryPath}31.jpg`, title: "Image 31", category: "default" },
  { src: `${galleryPath}32.jpg`, title: "Image 32", category: "default" },
  { src: `${galleryPath}33.jpg`, title: "Image 33", category: "default" },
  { src: `${galleryPath}34.jpg`, title: "Image 34", category: "default" },
  { src: `${galleryPath}35.jpg`, title: "Image 35", category: "default" },
  { src: `${galleryPath}36.jpg`, title: "Image 36", category: "default" },
  { src: `${galleryPath}37.jpg`, title: "Image 37", category: "default" },
  { src: `${galleryPath}38.jpg`, title: "Image 38", category: "default" },
  { src: `${galleryPath}39.jpg`, title: "Image 39", category: "default" },
  { src: `${galleryPath}40.jpg`, title: "Image 40", category: "default" },
  { src: `${galleryPath}41.jpg`, title: "Image 41", category: "default" },
  { src: `${galleryPath}42.jpg`, title: "Image 42", category: "default" },
  { src: `${galleryPath}43.jpg`, title: "Image 43", category: "default" },
  { src: `${galleryPath}44.jpg`, title: "Image 44", category: "default" },
  { src: `${galleryPath}45.jpg`, title: "Image 45", category: "default" },
  { src: `${galleryPath}46.jpg`, title: "Image 46", category: "default" },
  { src: `${galleryPath}47.jpg`, title: "Image 47", category: "default" },
  { src: `${galleryPath}48.jpg`, title: "Image 48", category: "default" },
  { src: `${galleryPath}49.jpg`, title: "Image 49", category: "default" },
  { src: `${galleryPath}50.jpg`, title: "Image 50", category: "default" },
  { src: `${galleryPath}51.jpg`, title: "Image 51", category: "default" },
  { src: `${galleryPath}52.jpg`, title: "Image 52", category: "default" },
  { src: `${galleryPath}53.jpg`, title: "Image 53", category: "default" },
  { src: `${galleryPath}54.jpg`, title: "Image 54", category: "default" },
  { src: `${galleryPath}55.jpg`, title: "Image 55", category: "default" },
  { src: `${galleryPath}56.jpg`, title: "Image 56", category: "default" },
  { src: `${galleryPath}57.jpg`, title: "Image 57", category: "default" },
];

export default images;
